name: meditation_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: '>=2.3.3 <3.0.0'

dependencies:
  rxdart: ^0.26.0
  upgrader: ^3.5.1
  mobx: ^2.0.4
  provider: ^5.0.0
  uuid: ^3.0.1
  path: ^1.6.4
  path_provider: ^2.0.1 
  photo_view: ^0.9.2
  equatable: ^1.1.0
  workmanager: ^0.2.0
  dartz: any
  get_it: ^2.0.1  
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.1  
  cloud_firestore: ^1.0.1
  collection: ^1.14.12
  shared_preferences: ^2.0.3
  flutter_spinkit: "^4.1.2"
  http: ^0.13.0
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.3.1
  wakelock: ^0.5.2
  google_sign_in: 5.0.0 
  webview_flutter: ^2.0.12
  flutter_circular_slider: ^2.5.0
  image_picker: ^0.7.3
  video_player: ^2.0.2
  firebase_storage: ^8.0.0
  plugin_platform_interface: ^2.0.0
  table_calendar: ^3.0.0
  assets_audio_player: ^3.0.1
  numberpicker: ^2.1.1
  flutter_html: ^2.1.0
  wheel_chooser: ^0.1.1
  connectivity_plus: ^1.0.5
  flutter_local_notifications: ^8.1.1+2
  firebase_messaging: ^10.0.8
  flutter_mobx: ^2.0.2




  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^2.0.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
 
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - assets/a_dot_burr.jpeg
  #  - assets/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/stage 1/
    - assets/stage 2/
    - assets/audios/
  fonts: 
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-regular.otf

    - family: Gotham-rounded
      fonts:
        - asset: fonts/GothamRounded.ttf
    
    - family: Helvetica
      fonts: 
        - asset: fonts/Helvetica.ttf
    
    - family: Gotham-bold
      fonts:
        - asset: fonts/GothamBold.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-assets/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-assets/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
