name: meditation_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.3.3 <3.0.0'

dependencies:
  rxdart: ^0.24.1
  bloc_provider: ^0.7.0
  observable: ^0.22.2
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.5
  google_fonts: ^0.2.0
  uuid: ^2.0.4
  path: ^1.6.4
  path_provider: ^1.6.1
  photo_view: ^0.9.2
  equatable: ^1.1.0
  workmanager: ^0.2.0
  dartz: any
  get_it: ^2.0.1  
  firebase_core: 0.4.4+3
  firebase_auth: ^0.16.0  
  cloud_firestore: ^0.13.5 
  cloud_firestore_mocks: ^0.4.2
  mock_cloud_firestore: ^0.0.20
  collection: ^1.14.12
  shared_preferences: ^0.5.6+2
  flutter_spinkit: "^4.1.2"
  assets_audio_player: ^2.0.13
  http: any
  data_connection_checker: any
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.3.1
  android_alarm_manager: ^0.4.5+17
  wakelock: ^0.2.1+1
  google_sign_in: ^4.5.6
  flutter_webview_plugin: ^0.3.10+1

  flutter:
  
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^1.0.3
  mockito: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
 
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - assets/a_dot_burr.jpeg
  #  - assets/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/stage 1/
    - assets/stage 2/
    - assets/audios/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-assets/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-assets/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
